spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/standard_dev
#    url: jdbc:mariadb://localhost:3306/standard_dev
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 9090